<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Tiempo de Inicio: lunes, 23 de diciembre de 2024 2:57:07 p. m.</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "C:\Users\mrivera\Documents\Proyectos\CSVExportFiberCopAddresses-\ExportToCSVFiberCop.py", line 234, in &lt;module&gt;
﻿    field_address, custom_names = prioritize_fields(field_address, custom_names)
﻿                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\mrivera\Documents\Proyectos\CSVExportFiberCopAddresses-\ExportToCSVFiberCop.py", line 199, in prioritize_fields
﻿    for base_field, new_field in field_priority.items():
﻿                                 ^^^^^^^^^^^^^^^^^^^^
﻿AttributeError: 'tuple' object has no attribute 'items'
</msg><msg code="0" type="0">Secuencia de comandos errónea Export to CSV Fiber Cop...</msg><msg code="-2147467259" type="100">Falló al ejecutar (ExportToCSVFiberCop).</msg><msg code="0" type="3">Falló el lunes, 23 de diciembre de 2024 2:57:08 p. m. (Tiempo transcurrido: 0,83 segundos)</msg></messages>